### ISSUE TITLE
Arquivo README.md

### ISSUE THREAD

**Issue by leandersonandre** [erickuniville/tcc#1]
ótima iniciativa Erick!
Vc pode adicionar um arquivo readme com as datas de entregas para o prof Romão.
e adicionar outros detalhes que forem importantes ao projeto.

**Comment by erickuniville** [comment]
Mais ou menos assim?

https://github.com/erickuniville/tcc/blob/master/README.md

**Comment by leandersonandre** [comment]
perfeito! isso mesmo,
Na ferramenta projects, vc pode criar um kanban no estilo trello.
